<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_org.openqa.selenium.devtools</name>
   <tag></tag>
   <elementGuidId>9d9076ee-345a-4aa1-b1ea-93b48c362968</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='all-packages-table']/div[2]/div[23]/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>95fadb04-50d1-4fec-ae6e-2e6d4e474e5c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>org/openqa/selenium/devtools/package-summary.html</value>
      <webElementGuid>231349c8-4957-4ac6-89bb-d96b0c503cb0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>org.openqa.selenium.devtools</value>
      <webElementGuid>da2bf27e-e15a-4e31-ae97-bcc627cc4ab2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;all-packages-table&quot;)/div[@class=&quot;summary-table two-column-summary&quot;]/div[@class=&quot;col-first even-row-color all-packages-table all-packages-table-tab1&quot;]/a[1]</value>
      <webElementGuid>f1c8bde1-6360-472f-af0a-aeb9c428f5af</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='all-packages-table']/div[2]/div[23]/a</value>
      <webElementGuid>04a5e8a3-94d1-413c-87b4-2158c27f860f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'org.openqa.selenium.devtools')]</value>
      <webElementGuid>db4e711f-66eb-486f-8d47-446761dc11ca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='org.openqa.selenium.concurrent'])[1]/following::a[1]</value>
      <webElementGuid>472b4965-fb7e-44cf-8835-1d96912c4302</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Mechanisms to configure and run selenium via the command line.'])[1]/following::a[2]</value>
      <webElementGuid>532e25e4-5bc0-46f1-9c38-2dd20601229c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='org.openqa.selenium.devtools.events'])[1]/preceding::a[1]</value>
      <webElementGuid>3bf90c3e-284c-4aeb-86c6-c9659eb009bd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='org.openqa.selenium.devtools.idealized'])[1]/preceding::a[2]</value>
      <webElementGuid>213da323-e93c-4794-b412-e0ba230af11d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='org.openqa.selenium.devtools']/parent::*</value>
      <webElementGuid>422024d0-1aa3-4421-8691-7f3c9e229922</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'org/openqa/selenium/devtools/package-summary.html')]</value>
      <webElementGuid>6e5dc719-68c8-42a4-a203-099f5809beab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[23]/a</value>
      <webElementGuid>a67c9f68-bf1c-4db9-94c1-1c61a5d5eb99</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'org/openqa/selenium/devtools/package-summary.html' and (text() = 'org.openqa.selenium.devtools' or . = 'org.openqa.selenium.devtools')]</value>
      <webElementGuid>8e5bd388-cf83-43ed-bede-c0df6f3bf116</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
